services:
  gogeturl:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ./gogeturl